export default [{
    "id": "0",
    "master_surname":"Shahinyan",
    "master_name": "Karen",
    "master_professions_id": [1, 2, 4, 6, 7],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "karen1962@gmail.com",
    "phone": ["055-62-88-81"],
    "description": "I am the best master ever",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "1",
    "master_surname":"Poxosyan",
    "master_name": "Aram",
    "master_professions_id": [5, 6, 3],
    "birth_date": new Date("1994-05-24"),
    "city": 0,
    "email": "arampoxosyan30@mail.ru",
    "phone": ["055765077", '093706909'],
    "description": "cankacac tipi veranorogman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "2",
    "master_surname":"Petrosyan",
    "master_name": "Nairi",
    "master_professions_id": [3, 2, 5],
    "birth_date": new Date("1988-05-24"),
    "city": 5,
    "email": "poghosHM@gmail.com",
    "phone": ["37485932288", "374859323"],
    "description": "",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "3",
    "master_surname":"Bagiryan",
    "master_name": "Andranik",
    "master_professions_id": [3, 4, 6],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "tigran30@inbox.ru",
    "phone": ["077216526"],
    "description": "katarumenq salikapatman ashxatanqner Inchpes " +
    "naev gipsakartoni, santexnikai " +
    "yev hosanqi montaji het kapvac ashxatanqner. " +
    "vorak@ yerashxavorumenq",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "4",
    "master_surname":"Sargsyan",
    "master_name": "Vardan",
    "master_professions_id": [4],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "sargsyanvardan@inbox.ru",
    "phone": ["093003063"],
    "description": "Katarumem elektrakan mantajner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "5",
    "master_surname":"Saroyan",
    "master_name": "Gevorg",
    "master_professions_id": [1, 2, 3, 4, 8],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "a_lusine@yahoo.com",
    "phone": ["094-05-24-50", "099-236-936"],
    "description": "Santexnika, Shinmotaj",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "6",
    "master_surname":"Enoyan",
    "master_name": "Manvel",
    "master_professions_id": [8, 12],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "enoyan32@mail.ru",
    "phone": ["099 92 92 21", "095712154"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "7",
    "master_surname":"Bidzyan",
    "master_name": "Sergey",
    "master_professions_id": [2, 4, 6, 7, 11],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "poghosHM@gmail.com",
    "phone": ["(055) 83-34-83", "(094) 91-12-02"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "8",
    "master_surname":"Malxasyan",
    "master_name": "Xachatur",
    "master_professions_id": [3, 8, 10],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "malxasyan28@mail.ru",
    "phone": ["095544233", "093544233"],
    "description": "svarka,avtogen,el.svarka,santexnika,qari mshakman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "9",
    "master_surname":"Hambaryan",
    "master_name": "Gevorg",
    "master_professions_id": [9],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "hambaryan28@inbox.ru",
    "phone": ["(093) 53-84-34", "(095) 53-94-50", "099826960"],
    "description": "katarum enq papuk kahuyqi veranorogum,nctatexeri " +
    "atorneri veranorogum,laqapatum naev patrastum nor noravoj bazmoc " +
    "bazkatorner, ankyunayin xoler taxtaner, pufer ev ayln, matcheli gin@ " +
    "ev bercr vorak@ erashxavorum enq.",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "10",
    "master_surname":"Shahinyan",
    "master_name": "Karen",
    "master_professions_id": [1, 2, 4, 6, 7],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "karen1962@gmail.com",
    "phone": ["055-62-88-81"],
    "description": "I am the best master ever",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "11",
    "master_surname":"Poxosyan",
    "master_name": "Aram",
    "master_professions_id": [5, 6, 3],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "arampoxosyan30@mail.ru",
    "phone": ["055765077", '093706909'],
    "description": "cankacac tipi veranorogman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "12",
    "master_surname":"Petrosyan",
    "master_name": "Nairi",
    "master_professions_id": [3, 2, 5],
    "birth_date": new Date("1988-05-24"),
    "city": 5,
    "email": "poghosHM@gmail.com",
    "phone": ["37485932288", "374859323"],
    "description": "",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "13",
    "master_surname":"Bagiryan",
    "master_name": "Andranik",
    "master_professions_id": [3, 4, 6],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "tigran30@inbox.ru",
    "phone": ["077216526"],
    "description": "katarumenq salikapatman ashxatanqner Inchpes " +
    "naev gipsakartoni, santexnikai " +
    "yev hosanqi montaji het kapvac ashxatanqner. " +
    "vorak@ yerashxavorumenq",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "14",
    "master_surname":"Sargsyan",
    "master_name": "Vardan",
    "master_professions_id": [4],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "sargsyanvardan@inbox.ru",
    "phone": ["093003063"],
    "description": "Katarumem elektrakan mantajner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "15",
    "master_surname":"Saroyan",
    "master_name": "Gevorg",
    "master_professions_id": [1, 2, 3, 4, 8],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "a_lusine@yahoo.com",
    "phone": ["094-05-24-50", "099-236-936"],
    "description": "Santexnika, Shinmotaj",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "16",
    "master_surname":"Enoyan",
    "master_name": "Manvel",
    "master_professions_id": [8, 12],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "enoyan32@mail.ru",
    "phone": ["099 92 92 21", "095712154"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "17",
    "master_surname":"Bidzyan",
    "master_name": "Sergey",
    "master_professions_id": [2, 4, 6, 7, 11],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "poghosHM@gmail.com",
    "phone": ["(055) 83-34-83", "(094) 91-12-02"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "18",
    "master_surname":"Malxasyan",
    "master_name": "Xachatur",
    "master_professions_id": [3, 8, 10],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "malxasyan28@mail.ru",
    "phone": ["095544233", "093544233"],
    "description": "svarka,avtogen,el.svarka,santexnika,qari mshakman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "19",
    "master_surname":"Hambaryan",
    "master_name": "Gevorg",
    "master_professions_id": [9],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "hambaryan28@inbox.ru",
    "phone": ["(093) 53-84-34", "(095) 53-94-50", "099826960"],
    "description": "katarum enq papuk kahuyqi veranorogum,nctatexeri " +
    "atorneri veranorogum,laqapatum naev patrastum nor noravoj bazmoc " +
    "bazkatorner, ankyunayin xoler taxtaner, pufer ev ayln, matcheli gin@ " +
    "ev bercr vorak@ erashxavorum enq.",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "20",
    "master_surname":"Shahinyan",
    "master_name": "Karen",
    "master_professions_id": [1, 2, 4, 6, 7],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "karen1962@gmail.com",
    "phone": ["055-62-88-81"],
    "description": "I am the best master ever",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "21",
    "master_surname":"Poxosyan",
    "master_name": "Aram",
    "master_professions_id": [5, 6, 3],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "arampoxosyan30@mail.ru",
    "phone": ["055765077", '093706909'],
    "description": "cankacac tipi veranorogman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "22",
    "master_surname":"Petrosyan",
    "master_name": "Nairi",
    "master_professions_id": [3, 2, 5],
    "birth_date": new Date("1988-05-24"),
    "city": 5,
    "email": "poghosHM@gmail.com",
    "phone": ["37485932288", "374859323"],
    "description": "",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "23",
    "master_surname":"Bagiryan",
    "master_name": "Andranik",
    "master_professions_id": [3, 4, 6],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "tigran30@inbox.ru",
    "phone": ["077216526"],
    "description": "katarumenq salikapatman ashxatanqner Inchpes " +
    "naev gipsakartoni, santexnikai " +
    "yev hosanqi montaji het kapvac ashxatanqner. " +
    "vorak@ yerashxavorumenq",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "24",
    "master_surname":"Sargsyan",
    "master_name": "Vardan",
    "master_professions_id": [4],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "sargsyanvardan@inbox.ru",
    "phone": ["093003063"],
    "description": "Katarumem elektrakan mantajner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "25",
    "master_surname":"Saroyan",
    "master_name": "Gevorg",
    "master_professions_id": [1, 2, 3, 4, 8],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "a_lusine@yahoo.com",
    "phone": ["094-05-24-50", "099-236-936"],
    "description": "Santexnika, Shinmotaj",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "26",
    "master_surname":"Enoyan",
    "master_name": "Manvel",
    "master_professions_id": [8, 12],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "enoyan32@mail.ru",
    "phone": ["099 92 92 21", "095712154"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "27",
    "master_surname":"Bidzyan",
    "master_name": "Sergey",
    "master_professions_id": [2, 4, 6, 7, 11],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "poghosHM@gmail.com",
    "phone": ["(055) 83-34-83", "(094) 91-12-02"],
    "description": "Դիմեք մեր հմուտ մասնագետներին, մենք կարճ ժամանակում կլինենք Ձեր հասցեում",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "divan", "kahuyq", "xol"],
    "notifications": []
},{
    "id": "28",
    "master_surname":"Malxasyan",
    "master_name": "Xachatur",
    "master_professions_id": [3, 8, 10],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "malxasyan28@mail.ru",
    "phone": ["095544233", "093544233"],
    "description": "svarka,avtogen,el.svarka,santexnika,qari mshakman ashxatanqner",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":["ator", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "29",
    "master_surname":"Hambaryan",
    "master_name": "Gevorg",
    "master_professions_id": [9],
    "birth_date": new Date("1988-05-24"),
    "city": 0,
    "email": "hambaryan28@inbox.ru",
    "phone": ["(093) 53-84-34", "(095) 53-94-50", "099826960"],
    "description": "katarum enq papuk kahuyqi veranorogum,nctatexeri " +
    "atorneri veranorogum,laqapatum naev patrastum nor noravoj bazmoc " +
    "bazkatorner, ankyunayin xoler taxtaner, pufer ev ayln, matcheli gin@ " +
    "ev bercr vorak@ erashxavorum enq.",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "tags":[ "divan", "kahuyq", "mebel", "xol"],
    "notifications": []
},{
    "id": "30",
    "master_surname":"Shahinyan",
    "master_name": "Sargis",
    "master_professions_id": [9],
    "birth_date": new Date("1996-03-26"),
    "city": 0,
    "email": "shahinyan.sargis@gmail.com",
    "phone": ["(094) 36-46-57", "(095) 36-46-57"],
    "description": "Test account",
    "public": true,
    "avatar_url":"images/master_photo_template.gif",
    "password": "saqo9662",
    "tags":["kompyuter", "hamakargich", "exungktrich", "akanjmtnuk", "huzmunq"],
    "notifications": [{
        active: true,
        subject: "Hy Sargis",
        message: "If you don't fix your profile, it will be deleted."
    }]
}]